program: src/pedestrians_video_2_carla/modeling.py
project: autoencoder
entity: carla-pedestrians
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args}
  - --skip_metadata
  - --disable_lr_scheduler
  - --mask_missing_joints
method: bayes
metric:
  goal: maximize
  name: hp/PCKhn@01
parameters:
  mode:
    value: train
  flow:
    value: autoencoder
  data_module_name:
    value: CarlaRecorded
  log_every_n_steps:
    value: 10
  num_sanity_val_steps:
    value: 1
  max_epochs:
    value: 500
  lr:
    max: 0.01
    min: 0.001
    distribution: uniform
  movements_model_name:
    value: Seq2SeqFlatEmbeddings
  renderers:
    value: none
  movements_output_type:
    value: pose_2d
  clip_offset:
    value: 15
  clip_length:
    value: 15
  batch_size:
    value: 256
  bidirectional:
    values:
      - False
      - True
  invert_sequence:
    values:
      - False
      - True
  hidden_size:
    max: 256
    min: 64
    distribution: int_uniform
  num_layers:
    max: 4
    min: 1
    distribution: int_uniform
  embeddings_size_0:
    max: 512
    min: 32
    distribution: int_uniform
  embeddings_size_1:
    max: 256
    min: 0
    distribution: int_uniform
  embeddings_size_2:
    max: 256
    min: 0
    distribution: int_uniform
  teacher_mode:
    value: frames_force
  teacher_force_ratio:
    min: 0.0
    max: 0.5
    distribution: uniform
  teacher_force_drop:
    min: 0.0001
    max: 0.02
    distribution: uniform
  transform:
    value: hips_neck_bbox
  missing_point_probability:
    value: 0.1
  noise_param:
    value: 1.0
  noise:
    value: gaussian